### ISSUE TITLE
Info.plist Key Issues in AndroidAutoUKey2Wrapper with XCode 15.x

### ISSUE THREAD

**Issue by mobile-suit-taurran** [google/android-auto-companion-ios#3]
Hello,

We're using the AndroidAutoUKey2Wrapper framework in our project with XCode 14. After updating to XCode **15.0**, we're unable to upload build archives to TestFlight due to missing CFBundleVersion and CFBundleShortVersionString keys in the framework's Info.plist.

![CleanShot 2024-01-24 at 15 30 43@2x](https://github.com/google/android-auto-companion-ios/assets/10552996/11f9635b-e064-490b-8eef-c2f9e00f385e)

Manually adding these keys resolves the issue. Could you please update the framework to include them?

Thanks for your support.

**Comment by tapsns** [comment]
Thanks for the feedback. We'll make the changes and get the change into an upcoming release. Thanks.

**Comment by tapsns** [comment]
I pushed a fix to the [hotfix branch](https://github.com/google/android-auto-companion-ios/tree/hotfix) for evaluation. Can you let me know whether that fixes the issue? Thanks.

**Comment by mobile-suit-taurran** [comment]
Thank you for your quick reply and support.
The hotfix branch fixes the issue !

**Comment by tapsns** [comment]
Great! Thanks for checking. I appreciate it. I've committed these changes internally, and they should be included in the release later this spring. It won't be included in the February release because that one has already passed QA so it's too late to make any changes in it.
