### ISSUE TITLE
Cannot use v4.0.1 of this SDK with android-auto-companion-calendarsync-ios v3.0.0

### ISSUE THREAD

**Issue by lyamamot** [google/android-auto-companion-ios#4]
The current version of this SDK is v4.0.1. If I try to use both this SDK with the calendar sync SDK, there is a dependency resolution error because the calendar sync SDK requires a version of this SDK [between v3.1.0 and below v4.0.0](https://github.com/google/android-auto-companion-calendarsync-ios/blob/70feea4d73ba63b6e3a4bac4b7fa071dfef937d1/Package.swift#L30).

I am looking to integrate at least version v3.4.0 of this SDK to [solve an app submission issue](https://github.com/google/android-auto-companion-ios/blob/80415772bb4f59534e626706accbf7e3ab113682/CHANGELOG.md?plain=1#L15) with the UKey2Wrapper framework on Xcode 15, but no such version v3.4.0 of this SDK is tagged.

Please update the calendar sync SDK to use v4 of this SDK or please tag this SDK with v3.4.0.

**Comment by tapsns** [comment]
Thanks for reporting the issue. I've pushed out the Calendar Sync 4 release that fixes the issue as you suggested.
